### ISSUE TITLE
Related to your other mod Perished Plains (Srry for posting this here)

### ISSUE THREAD

**Issue by JuanSe582** [c0d3break3r/Omni#13]
The Asphodel Bookshelf and Asphodel Beehive have a missing texture
![2020-11-08_16 02 51](https://user-images.githubusercontent.com/74156254/98484220-e9dc1080-21db-11eb-911a-205a395e92ac.png)
![2020-11-08_16 02 53](https://user-images.githubusercontent.com/74156254/98484222-eba5d400-21db-11eb-96ad-cca6de234d33.png)

**Comment by c0d3break3r** [comment]
I never made textures for those two blocks. I may in the future but for now Omni is a priority. Please keep the issues here related to the mod. Perished Plains was just a one-time thing that may be improved later on.
