### ISSUE TITLE
Suggestion (?) - Malachite Crystals

### ISSUE THREAD

**Issue by Blugori** [c0d3break3r/Omni#15]
Hi !
I was wondering if you were planning to make the malachite crystals/geode generate in a 1.16 world, before 1.17 arise ?

Thanks for reading, the mod is awesome !

**Comment by c0d3break3r** [comment]
I would like to do this but I am currently focused on bugfixing. I will also have to come up with a worthwhile use for these crystals before making them available in survival.

Glad you like the mod!

**Comment by Blugori** [comment]
Are you open to suggestions ?
 (code breaker is a nice anime btw)

**Comment by c0d3break3r** [comment]
They now generate in the latest release. It was surprisingly not that time consuming
