### ISSUE TITLE
Stone Speleothems generate on most blocks in ocean caves (1.16.1)

### ISSUE THREAD

**Issue by dabomb6405** [c0d3break3r/Omni#16]
![bug](https://user-images.githubusercontent.com/66895105/98501442-77cfef80-220c-11eb-9f5e-bb65fb794c2c.png)

In all ocean biomes, every single cave generates like this. I was looking at this in spectator and can't imagine the nightmare that would be traversing this in survival.

**Comment by c0d3break3r** [comment]
yeah that clearly is an issue. ill release a hotfix in a little while for this
