### ISSUE TITLE
Malachite geodes interfere with underground structures

### ISSUE THREAD

**Issue by ChrissPz** [c0d3break3r/Omni#20]
![2020-11-14_02 55 30](https://user-images.githubusercontent.com/33664951/99141662-469c5880-262c-11eb-81b5-4787a92ec18e.png)

![2020-11-14_02 54 23](https://user-images.githubusercontent.com/33664951/99141685-97ac4c80-262c-11eb-82ce-f8ee976f3015.png)

![2020-11-14_02 55 14](https://user-images.githubusercontent.com/33664951/99141690-9d099700-262c-11eb-96b3-1061b1b70c24.png)

If it detects structures it shouldn't be generated in that place. i think

**Comment by c0d3break3r** [comment]
Structures are generated after world features, such as the Geodes. This issue is being caused by the other mod.
