### ISSUE TITLE
potted,translated

### ISSUE THREAD

**Issue by Pancakes0228** [c0d3break3r/Omni#21]
The lotus flowers in flower Pot,maybe
I translated the mod(from Taiwan).But i am not familiar GitHub.

**Comment by c0d3break3r** [comment]
Lotus flowers will be able to be put into flower pots in the future.
If you translated the mod you can create a pull request or just put a link to the file here if you are having problems. Thank you :D

**Comment by Pancakes0228** [comment]
{
  "_comment": "Cavier Caves",

  "block.omni.stone_speleothem": "石灰華",
  "block.omni.ice_speleothem": "冰晶柱",
  "block.omni.netherrack_speleothem": "地獄石灰華",

  "block.omni.malachite_block": "孔雀石方塊",
  "block.omni.budding_malachite": "出芽孔雀石",
  "block.omni.malachite_cluster": "孔雀石簇",
  "block.omni.large_malachite_bud": "大孔雀石芽",
  "block.omni.medium_malachite_bud": "中孔雀石芽",
  "block.omni.small_malachite_bud": "小孔雀石芽",

  "_comment1": "Colormatic",

  "block.omni.brown_quilted_carpet": "棕色綢緞地毯",
  "block.omni.red_quilted_carpet": "紅色綢緞地毯",
  "block.omni.orange_quilted_carpet": "橙色綢緞地毯",
  "block.omni.yellow_quilted_carpet": "黃色綢緞地毯",
  "block.omni.lime_quilted_carpet": "淺綠色綢緞地毯",
  "block.omni.green_quilted_carpet": "綠色綢緞地毯",
  "block.omni.cyan_quilted_carpet": "青色綢緞地毯",
  "block.omni.blue_quilted_carpet": "藍色綢緞地毯",
  "block.omni.light_blue_quilted_carpet": "淺藍色綢緞地毯",
  "block.omni.pink_quilted_carpet": "粉色綢緞地毯",
  "block.omni.magenta_quilted_carpet": "洋紅色綢緞地毯",
  "block.omni.purple_quilted_carpet": "紫色綢緞地毯",
  "block.omni.black_quilted_carpet": "黑色綢緞地毯",
  "block.omni.gray_quilted_carpet": "灰色綢緞地毯",
  "block.omni.light_gray_quilted_carpet": "淺灰色綢緞地毯",
  "block.omni.white_quilted_carpet": "白色綢緞地毯",
  "block.omni.traders_quilted_carpet": "商人的綢緞地毯",

  "block.omni.brown_quilted_wool": "棕色綢緞羊毛",
  "block.omni.red_quilted_wool": "紅色綢緞羊毛",
  "block.omni.orange_quilted_wool": "橙色綢緞羊毛",
  "block.omni.yellow_quilted_wool": "黃色綢緞羊毛",
  "block.omni.lime_quilted_wool": "淺綠色綢緞羊毛",
  "block.omni.green_quilted_wool": "綠色綢緞羊毛",
  "block.omni.cyan_quilted_wool": "青色綢緞羊毛",
  "block.omni.blue_quilted_wool": "藍色綢緞羊毛",
  "block.omni.light_blue_quilted_wool": "淺藍色綢緞羊毛",
  "block.omni.pink_quilted_wool": "粉色綢緞羊毛",
  "block.omni.magenta_quilted_wool": "洋紅色綢緞羊毛",
  "block.omni.purple_quilted_wool": "紫色綢緞羊毛",
  "block.omni.black_quilted_wool": "黑色綢緞羊毛",
  "block.omni.gray_quilted_wool": "灰色綢緞羊毛",
  "block.omni.light_gray_quilted_wool": "淺灰色綢緞羊毛",
  "block.omni.white_quilted_wool": "白色綢緞羊毛",
  "block.omni.traders_quilted_wool": "商人的綢緞羊毛",

  "block.omni.brown_concrete_powder": "棕色混凝土粉末",
  "block.omni.red_concrete_powder": "紅色混凝土粉末",
  "block.omni.orange_concrete_powder": "橙色混凝土粉末",
  "block.omni.yellow_concrete_powder": "黃色混凝土粉末",
  "block.omni.lime_concrete_powder": "淺綠色混凝土粉末",
  "block.omni.green_concrete_powder": "綠色混凝土粉末",
  "block.omni.cyan_concrete_powder": "青色混凝土粉末",
  "block.omni.blue_concrete_powder": "藍色混凝土粉末",
  "block.omni.light_blue_concrete_powder": "淺藍色混凝土粉末",
  "block.omni.pink_concrete_powder": "粉色混凝土粉末",
  "block.omni.magenta_concrete_powder": "洋紅色混凝土粉末",
  "block.omni.purple_concrete_powder": "紫色混凝土粉末",
  "block.omni.black_concrete_powder": "黑色混凝土粉末",
  "block.omni.gray_concrete_powder": "灰色混凝土粉末",
  "block.omni.light_gray_concrete_powder": "淺色混凝土粉末",
  "block.omni.white_concrete_powder": "白色混凝土粉末",

  "block.omni.brown_concrete": "棕色混凝土",
  "block.omni.red_concrete": "紅色混凝土",
  "block.omni.orange_concrete": "橙色混凝土",
  "block.omni.yellow_concrete": "黃色混凝土",
  "block.omni.lime_concrete": "淺綠色混凝土",
  "block.omni.green_concrete": "綠色混凝土",
  "block.omni.cyan_concrete": "青色混凝土",
  "block.omni.blue_concrete": "藍色混凝土",
  "block.omni.light_blue_concrete": "淺藍色混凝土",
  "block.omni.pink_concrete": "粉色混凝土",
  "block.omni.magenta_concrete": "洋紅色混凝土",
  "block.omni.purple_concrete": "紫色混凝土",
  "block.omni.black_concrete": "黑色混凝土",
  "block.omni.gray_concrete": "灰色混凝土",
  "block.omni.light_gray_concrete": "淺灰色混凝土",
  "block.omni.white_concrete": "白色混凝土",

  "block.omni.white_glazed_terracotta_pillar": "白色釉陶柱",
  "block.omni.orange_glazed_terracotta_pillar": "橙色釉陶柱",
  "block.omni.magenta_glazed_terracotta_pillar": "洋紅色釉陶柱",
  "block.omni.light_blue_glazed_terracotta_pillar": "淺藍色釉陶柱",
  "block.omni.yellow_glazed_terracotta_pillar": "黃色釉陶柱",
  "block.omni.lime_glazed_terracotta_pillar": "淺綠色釉陶柱",
  "block.omni.pink_glazed_terracotta_pillar": "粉色釉陶柱",
  "block.omni.gray_glazed_terracotta_pillar": "灰色釉陶柱",
  "block.omni.light_gray_glazed_terracotta_pillar": "淺灰色釉陶柱",
  "block.omni.cyan_glazed_terracotta_pillar": "青色釉陶柱",
  "block.omni.purple_glazed_terracotta_pillar": "紫色釉陶柱",
  "block.omni.blue_glazed_terracotta_pillar": "藍色釉陶柱",
  "block.omni.brown_glazed_terracotta_pillar": "棕色釉陶柱",
  "block.omni.green_glazed_terracotta_pillar": "綠色釉陶柱",
  "block.omni.red_glazed_terracotta_pillar": "紅色釉陶柱",
  "block.omni.black_glazed_terracotta_pillar": "黑色釉陶柱",

  "block.omni.alliums": "紫紅球花",
  "block.omni.azure_bluets": "雛草",
  "block.omni.blue_orchids": "藍色蝴蝶蘭",
  "block.omni.cornflowers": "矢車菊",
  "block.omni.dandelions": "蒲公英",
  "block.omni.lily_of_the_valleys": "鈴蘭",
  "block.omni.orange_tulips": "橙色鬱金香",
  "block.omni.oxeye_daisys": "雛菊",
  "block.omni.pink_tulips": "粉色鬱金香",
  "block.omni.poppys": "罌粟",
  "block.omni.red_tulips": "紅色鬱金香",
  "block.omni.white_tulips": "白色鬱金香",
  "block.omni.wither_roses": "凋零玫瑰",
  "block.omni.red_mushrooms": "紅色蘑菇",
  "block.omni.brown_mushrooms": "棕色蘑菇",
  "block.omni.crimson_fungi": "緋紅蕈菇",
  "block.omni.warped_fungi": "扭曲蕈菇",

  "entity.omni.falling_concrete_powder": "落下的混凝土粉末",

  "biome.omni.flower_field": "繁花平原",

  "_comment2": "Deserted",

  "block.omni.red_rock": "紅層岩",
  "block.omni.red_rock_stairs": "紅層岩階梯",
  "block.omni.red_rock_slab": "紅層岩半磚",
  "block.omni.red_rock_vertical_slab": "紅層岩半牆",
  "block.omni.red_rock_wall": "紅層岩牆",
  "block.omni.red_rock_bricks": "紅層岩磚",
  "block.omni.red_rock_brick_stairs": "紅層岩磚階梯",
  "block.omni.red_rock_brick_slab": "紅層岩磚半磚",
  "block.omni.red_rock_brick_vertical_slab": "紅層岩磚半牆",
  "block.omni.red_rock_brick_wall": "紅層岩磚牆",
  "block.omni.chiseled_red_rock_bricks": "浮雕紅層岩磚",
  "block.omni.cracked_red_rock_bricks": "裂紋紅層岩磚",
  "block.omni.red_rock_pillar": "紅層岩柱",
  "block.omni.red_rock_brick_button": "紅層岩磚按鈕",
  "block.omni.red_rock_brick_pressure_plate": "紅層岩磚壓力板",
  "block.omni.red_rock_vertical_slab": "紅層岩垂直半磚",
  "block.omni.red_rock_brick_vertical_slab": "紅層岩磚垂直半磚",
  "block.omni.red_rock_pavement": "紅層岩徑",

  "_comment3": "Forestry",

  "subtitles.ambient.forest": "蟲鳴鳥叫",
  "subtitles.ambient.jungle": "異常的聲音",
  "subtitles.ambient.plains": "鄉村氛圍",
  "subtitles.ambient.swamp": "隱約的聲音",

  "_comment4": "Paradise",

  "block.omni.red_lotus_flower": "紅色蓮花",
  "block.omni.orange_lotus_flower": "橘色蓮花",
  "block.omni.yellow_lotus_flower": "黃色蓮花",
  "block.omni.blue_lotus_flower": "藍色蓮花",
  "block.omni.pink_lotus_flower": "粉色蓮花",
  "block.omni.purple_lotus_flower": "紫色蓮花",
  "block.omni.black_lotus_flower": "黑色蓮花",
  "block.omni.white_lotus_flower": "白色蓮花"
}

**Comment by Pancakes0228** [comment]
This is 1.16.1 zh_tw files.I just finished the midterm exam so I'm late.
