### ISSUE TITLE
Bug - Compatibility - No loot in some chests

### ISSUE THREAD

**Issue by Blugori** [c0d3break3r/Omni#23]
Hi, I ran into an issue while using Omni 1.1.0

When I created a new world, and found a desert pyramid, chests in it were empty.

This issue happen when at least one of these 3 mods is installed : 
Ice and Fire 2.1.2
Enigmatic Legacy 2.10.0
Pandora's Creatures 2.0.1

Minecraft config : 
Minecraft : 1.16.4
Forge : 35.1.0
Optifine : 1.16.4_HD_U_G5
Omni : 1.1.0
(I also tested Omni 1.1.5+Ice and fire, and got the same results)

Let me know if you need more logs (by example logs for every configuration)

Logs for Omni 1.1.5 + Ice and Fire : 
[debug.log](https://github.com/c0d3break3r/Omni/files/5585163/debug.log)
[latest.log](https://github.com/c0d3break3r/Omni/files/5585164/latest.log)

Your mod really is awesome ! I'd love to play with 😅

Best regards 🙂

**Comment by Extegral** [comment]
Joining this to point out to exact line of code that needs alteration to fix this:

https://github.com/c0d3break3r/Omni/blob/79b968db7b088ad9374a208ee072a9c2b1f19bf0/src/main/java/pugz/omni/core/module/MiscellaneousModule.java#L153

You should ALWAYS set a name for `LootPool` you are injecting, by calling `LootPool.Builder#name(String)` method and thus setting it to... whatever, just make sure that whatever is not null. That will avoid all of that `NullPointerException` action going on in the presented log and no loot generated from affected tables as a result.

**Comment by c0d3break3r** [comment]
Fixed in the next release. Just updated Omni and testing it with Ice and Fire: loot is generating.

**Comment by Extegral** [comment]
👍
