### ISSUE TITLE
Omni replaces the vanilla Concrete Powder, preventing other mods from solidifying it

### ISSUE THREAD

**Issue by DaedalusGame** [c0d3break3r/Omni#24]
Things like Quark's module that solidifies concrete items when dropped in water or Create's washing mechanic do not work on Omni concrete and there should probably be a config toggle to keep the vanilla concrete with a conversion recipe for turning vanilla concrete into omni concrete.

**Comment by whorlbinder** [comment]
Yeah, just something in the configs would be nice. The Omni concrete features are really neat, but compat's an issue and there's more to Omni than just that.

**Comment by c0d3break3r** [comment]
Just changed from doing registry replacement to a more compatible method, hopefully this fixes any issues. There will be config options to disable features in the future. Also I'm not aware of Quark adding a feature like that, did a quick search and I found nothing 😕

**Comment by DaedalusGame** [comment]
oh i could swear it did, but there's usually atleast 1 mod on each version that lets you dump concrete into water to quickly harden it
