### ISSUE TITLE
Config option for disabling ambient sounds

### ISSUE THREAD

**Issue by DaedalusGame** [c0d3break3r/Omni#25]
Please it plays all the way down to bedrock at pretty much any time, day and night, it's driving everybody on our server kinda insane

**Comment by c0d3break3r** [comment]
I'm very sorry you guys are going insane lol. I'll put out a version tonight with some more config options

**Comment by DaedalusGame** [comment]
thank you very much, like i don't want to knock them, but because of that problem and because you'd probably not even want them if you were running another ambience mod like Charmonium, i think a config is kind of necessary

**Comment by c0d3break3r** [comment]
I've decided to just remove the sounds; I was considering doing this ever since I added them actually. Now since Charmonium is a thing, there's no need for them anymore
