### ISSUE TITLE
Flower Field Generating In The End

### ISSUE THREAD

**Issue by JuanSe582** [c0d3break3r/Omni#34]
Flower Field Is Generating In The End

**Comment by JuanSe582** [comment]
Version 1.2.1

**Comment by JuanSe582** [comment]
It generates in all outer end islands

**Comment by JuanSe582** [comment]
![2021-01-01_17 29 04](https://user-images.githubusercontent.com/74156254/103447277-e783b900-4c56-11eb-9f9c-581949bdc391.png)

**Comment by JuanSe582** [comment]
If you create a new world it doesn't happens don't know what happened here

**Comment by c0d3break3r** [comment]
By any chance are you using the forge port of BetterEnd?

**Comment by Epic312** [comment]
Looking at the sky that's definitely BetterEnd. It does some wacky stuff with how it registers biomes - definitely an issue on their end, not Omni's.

**Comment by c0d3break3r** [comment]
yeah im like 99.9% sure that BetterEnd is the problem here. Closing this
